config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    sessions: 'users/sessions'
  }

  root to: 'tops#index'
  
  resources :users, only: [:index, :show] do
    patch :update_eat_day, on: :member
  end 

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :posts do
    resource :likes, only: [:create, :destroy]
    resource :comments, only: [:new, :create]
    resources :comments, only: [:edit, :update, :destroy]
  end

  resources :informations, only: [:index, :show]
  match '*unmatched_route' => 'application#routing_error', via: :all
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :email, length: { maximum: 255 }, uniqueness: true
  validates :cost, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :profile, length: { maximum: 160 }

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  mount_uploader :image, ImageUploader

  # 当日中にお菓子を止めた日数をカウントする
  COUNT_STOPDAY_TODAY = 1

  # サービス利用開始日からお菓子を止めた日数を算出する
  def calc_stop_day
    (Date.current - self.created_at.to_date).to_i + COUNT_STOPDAY_TODAY - self.eat_day
  end

  # サービス利用開始時からお菓子を止めたことによる節約金額を算出する
  def save_money
    self.cost * calc_stop_day
  end

  # 1ヶ月間のお菓子を止めたことによる節約金額を算出する
  def save_money_month
    self.cost * calc_stop_day_month
  end

  # 今月のお菓子を止めた日数を算出する
  def calc_stop_day_month
    start_date = if Date.today.beginning_of_month >= self.created_at
      Date.today.beginning_of_month
    else
      self.created_at.to_date
    end

    (Date.today - start_date).to_i  + COUNT_STOPDAY_TODAY - self.eat_day_month
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザ"
      user.cost = 500
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == "guest@example.com"
      redirect_to new_user_session_path, alert: "ゲストユーザーのパスワード再設定はできません。"
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == "guest@example.com"
      redirect_to user_path(current_user), alert: "ゲストユーザーの更新・削除はできません。"
    end
  end

  def after_sign_up_path_for(resource)
    #アカウント登録後のリダイレクト先
    user_path(resource)
  end

  def after_update_path_for(resource)
    #アカウント登録後のリダイレクト先
    user_path(resource)
  end

  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    # ゲストアカウントでログイン
    sign_in User.guest
    # マイページへリダイレクト
    redirect_to user_path(current_user), notice: "ゲストユーザーとしてログインしました。"
  end

  def after_sign_in_path_for(resource)
    #ログイン後のリダイレクト先
    user_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    # ユーザが1ヶ月間お菓子を止めた日数のランキングを表示するSQL。
    # ランキングの算出方法は本日 - 月初（もし、月初以降にアプリを使い始めた場合、アプリを使い始めた日） - お菓子を食べてしまった日数
    # ランキングに表示可能なユーザは100名までとする。
    @users = User.find_by_sql(
    "SELECT *, DENSE_RANK() OVER(ORDER BY STOP_DAY DESC) AS RANK
     FROM (SELECT ID, NAME, IMAGE,
            (CASE
              WHEN CAST(CREATED_AT AS DATE) > CAST(DATE_TRUNC('MONTH', NOW()) AS DATE)
              THEN CURRENT_DATE - CAST(CREATED_AT AS DATE) - EAT_DAY_MONTH
              ELSE CURRENT_DATE - CAST(DATE_TRUNC('MONTH', NOW()) AS DATE) - EAT_DAY_MONTH END) AS STOP_DAY
           FROM USERS) AS STOP_DAY_COUNT
     LIMIT 100")
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: (params[:id])).includes(:user)
  end

  def update_eat_day
    @user = User.find(params[:id])
    if @user.eat_day_updated_on != Date.today && @user.calc_stop_day > 0
      @user.update!(eat_day: @user.eat_day + 1, eat_day_month: @user.eat_day_month + 1, eat_day_updated_on: Date.today)
      flash[:notice] = "本日お菓子を食べたことを申告されました。<br>お菓子を止めた日数、節約金額に申告結果が反映されました"
    else
      flash[:alert] = "本日はこれ以上、申告できません"
    end
    redirect_back(fallback_location: user_path(@user))
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_crown(rank_status)
     case rank_status
     when 1 then
      image_tag '王冠 金.jpeg'
     when 2 then
      image_tag '王冠 銀.jpeg'
     when 3 then
      image_tag '王冠 銅.jpeg'
    end
  end

  def display_user_icon(instance, icon_property, icon_property2="")
    if instance.image?
      image_tag instance.image.url, class: "#{icon_property} #{icon_property2}"
    else
      image_tag 'no-image.png', class: "#{icon_property} #{icon_property2}"
    end
  end
end

app/views/users/_post.html.erb
<div class="mypage-post-content">
  <% if post.user.image? %>
    <%= link_to image_tag(post.user.image.url, class: "mypage-show_image"), post_path(post) %>
  <% else %>
    <%= link_to image_tag('no-image.png', class: "mypage-show_image"), post_path(post) %>
  <% end %>
  <strong class="mypage-user-name">
    <%= link_to post.user.name, user_path(post.user), class:"link_under_none" %>
  </strong>
  <%= link_to(post_path(post), class: "tweet_content") do %>
    <div class="mypage-content">
      <%= post.content %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<tr> 
  <td class="align-middle text-center rank-info">
    <%= user.rank %>
  </td>
  <td class="align-middle user-name-diplays">
    <%= display_user_icon(user, "show-user-image", "rounded-circle") %>
    <div class="d-inline-block">
      <strong><%= link_to user.name, user_path(user.id), class:"link_under_none align-middle"%></strong>
    </div>
  </td>
  <td class="align-middle text-center rank-info-continue">
    <%= user.stop_day %>
  </td>
  <td class="align-middle text-center">
    <%= display_crown(user.rank) %>
  </td>
</tr>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
  <div class="col-lg-3"></div>
    <div class="col-lg-7">
      <table class="table">
        <thead class="table-head text-white bg-secondary">
          <tr>
            <th width= 20% class="text-center">順位</th>
            <th width= 40% class="rank-user-name">ユーザー名</th>
            <th width= 30% class="text-center">継続日数</th>
            <th width= 10% class="text-center"></th>
          </tr>
        </thead>
        <tbody>
          <%= render @users %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-end">
    <div class="col-lg-4 mb-lg-5 mr-lg-5 mb-5">
      <% if current_user.id == @user.id %>
        <div class="text-right">
          <%=link_to("お菓子を食べた", update_eat_day_user_path(@user), method: :patch, class: "btn btn-primary mt-3")%>
        </div>
      <% end %>  
      <div class="user-image text-center mb-4">
        <%= display_user_icon(@user, "show-image", "rounded-circle") %>
      </div>
      <div class="text-center mb-5">
        <h4><strong><%= @user.name %></strong></h4>
      </div>
      <table class="table table-striped table-bordered">
        <% if current_user.id == @user.id %>
          <tr>
            <th class="h5"><strong>メールアドレス</strong></th>
          </tr>
          <tr>
            <th class="font-weight-normal"><%= @user.email %></th>
          </tr>
        <% end %>
        <tr>
          <th class="h5"><strong>サービス利用開始日</strong></th>
        </tr>
        <tr>
          <th class="font-weight-normal"><%= l @user.created_at %></th>
        </tr>
        <tr>
          <th class="h5"><strong>サービス利用開始からお菓子を止めた日数</strong></th>
        </tr>
        <tr>
          <th class="font-weight-normal change-color"><%= @user.calc_stop_day %>日</th>
        </tr>
        <tr>
          <th class="h5"><strong>サービス利用開始から節約した金額</strong></th>
        </tr>
        <tr>
          <th class="font-weight-normal change-color"><%= @user.save_money %>円</th>
        </tr>
        <tr>
          <th class="h5"><strong>今月のお菓子を止めた日数</strong></th>
        </tr>
        <tr>
          <th class="font-weight-normal change-color"><%= @user.calc_stop_day_month %>日</th>
        </tr>
        <tr>
          <th class="h5"><strong>今月の節約した金額</strong></th>
        </tr>
        <tr>
          <th class="font-weight-normal change-color"><%= @user.save_money_month %>円</th>
        </tr>
      </table>
      <% if current_user.id == @user.id && @user.name != "ゲストユーザ" %>
        <div class="mypage-button-info">
          <%=link_to("編集", edit_user_registration_path, class: "btn btn-info mypage-button")%>
          <%=link_to("削除", user_registration_path, method: :delete, class: "btn btn-info mypage-button", data: { confirm: '本当に削除しますか？' } )%>
        </div>
      <% end %>
    </div>
    <div class="col-lg-3 ml-lg-5 mt-1 mb-5">
      <% if @user.profile.present? %>
        <h5 class=" mt-lg-5"><strong>プロフィール</strong></h5>
        <div class="mypage-profile">
          <%= @user.profile %>
        </div>
        <br>
      <% end %>
      <% if @posts.present? %>
        <h5 class=" mt-lg-5"><strong>つぶやき一覧</strong></h5>
        <div class="mypage-content-scroll">
          <%= render partial: 'post', collection: @posts %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'show' %>