config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    sessions: 'users/sessions'
  }

  root to: 'tops#index'
  
  resources :users, only: [:index, :show] do
    patch :update_eat_day, on: :member
  end 

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :posts do
    resource :likes, only: [:create, :destroy]
    resource :comments, only: [:new, :create]
    resources :comments, only: [:edit, :update, :destroy]
  end

  resources :informations, only: [:index, :show]
  match '*unmatched_route' => 'application#routing_error', via: :all
end

app/models/information.rb
class Information < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  before_action :authenticate_user!

  # 1ページの表示数
  PER_PAGE = 5

  def index
    @informations = Information.order(created_at: :desc).page(params[:page]).per(PER_PAGE)
  end

  def show
    @information = Information.find(params[:id])
  end
end

app/views/informations/_information.html.erb
<table class="table">
  <tbody>
    <tr>
      <td>
        <p class="posted_day"><%= l information.created_at %>に投稿</p>
        <h2><%= link_to information.title, information_path(information.id), class:"link_under_none_post" %></h2>
      </td>
    </tr>
  </tbody>
</table>
      

app/views/informations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3"></div>
      <div class="col-lg-7 mb-5">
        <%= paginate @informations %>
        <%= render partial: 'information', collection: @informations %>
        <%= paginate @informations %>
      </div>
    </div>
  </div>
</div>

app/views/informations/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8 my-lg-5 mb-5">
      <%= markdown(@information.content) %>
      <%= link_to("戻る", informations_path,  class: "btn btn-secondary btn-lg btn-block btn-back") %>
    </div>
  </div>
</div>