config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    sessions: 'users/sessions'
  }

  root to: 'tops#index'
  
  resources :users, only: [:index, :show] do
    patch :update_eat_day, on: :member
  end 

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :posts do
    resource :likes, only: [:create, :destroy]
    resource :comments, only: [:new, :create]
    resources :comments, only: [:edit, :update, :destroy]
  end

  resources :informations, only: [:index, :show]
  match '*unmatched_route' => 'application#routing_error', via: :all
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :content, presence: true, length: { maximum: 140 }

  def liked_by?(user)
    likes.any? { |like| like.user_id == user.id }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[edit update destroy]

  # 1ページの表示数
  PER_PAGE = 5

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.includes(:user, :likes).order(created_at: "DESC").page(params[:page]).per(PER_PAGE)
    # つぶやきが1件も投稿されていなかった場合につぶやき一覧以外のページから遷移された際にメッセージが出力されることを防ぐ
    if request.referer&.include?("posts")
      # 検索バーにキーワードが入力されている状態かつ検索結果がなかった場合にメッセージを出力させる
      flash.now[:alert] = "検索に一致するつぶやきはありませんでした" if @posts.empty? && params[:q][:content_cont].present?
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    (@post.save) ? (redirect_to posts_path) : (render :new)
  end

  def show
    @post = Post.includes(comments: :user).find(params[:id])
    @comment = Comment.new
  end

  def edit
  end

  def update
    (@post.update(post_params)) ? (redirect_to posts_path) : (render :edit)
  end

  def destroy
    @post.destroy!
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def display_user_icon_post(instance, icon_property="", routing)
    if instance.image?
      link_to image_tag(instance.image.url, class: "#{icon_property}"), routing
    else
      link_to image_tag('no-image.png', class: "#{icon_property}"), routing
    end
  end
end

app/views/posts/_comment.html.erb
<div class="post-detail-content">
  <%= display_user_icon_post(comment.user, "show_image", user_path(comment.user)) %>
  <strong class="user-name">
    <%= link_to comment.user.name, user_path(comment.user), class:"link_under_none" %>
  </strong>
  <% if current_user.id == comment.user_id %>
    <div class="dropdown">
      <button class="btn fa fa-ellipsis-v" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      </button>
      <div class="dropdown-menu  dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to "編集", edit_post_comment_path(comment), class:"dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to "削除", post_comment_path(comment), method: :delete, data: { confirm: "削除しますか？" }, class:"dropdown-item" %>
      </div>
    </div>
  <% end %>
  <div class="content">
    <p><%= comment.content %></p>
  </div>
  <div class="tweet-time">
    <%= l comment.updated_at %>
  </div>
</div>

app/views/posts/_dislike.html.erb
<%= link_to "", post_likes_path(post), class: "fa fa-heart fa-lg dislike-info", method: :post, remote: true %>
<%= post.likes.size %>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
  <%= f.text_area :content, required: true, size:"20x10", class: "form-control" %><br>
  <%= f.submit class: "btn btn-info btn-lg btn-block" %>
<% end %>

app/views/posts/_like.html.erb
<%= link_to "", post_likes_path(post), class: "fa fa-heart fa-lg like-info", method: :delete, remote: true %>
<%= post.likes.size %>

app/views/posts/_post.html.erb
<div class="post-content">
  <%= display_user_icon_post(post.user, "show_image", user_path(post.user)) %>
  <%= render 'post_header', post: post %>
  <%= link_to(post_path(post), class: "tweet_content") do %>
    <div class="content">
      <%= post.content %>
    </div>
  <% end %>
  <%= render 'post_footer', post: post %>
</div>

app/views/posts/_post_footer.html.erb
<div class="tweet-time">
  <%= l post.updated_at %>
</div>
<div class="post-icon">
  <span id="post-<%= post.id %>">
    <% if post.liked_by?(current_user) %>
      <%= render "like", post: post %>
    <% else %>
      <%= render "dislike", post: post %>
    <% end %>
  </span>
</div>
<div class="comment-icon">
  <%= link_to "", post_path(post), class:"fa fa-comment fa-lg comment-style" %>
  <%= post.comments_count %>
</div>

app/views/posts/_post_header.html.erb
<strong class="user-name">
  <%= link_to post.user.name, user_path(post.user), class:"link_under_none" %>
</strong>
<% if current_user.id == post.user_id %>
  <div class="dropdown">
    <button class="btn fa fa-ellipsis-v" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    </button>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
      <%= link_to "編集", edit_post_path(post), class:"dropdown-item" %>
      <div class="dropdown-divider"></div>
      <%= link_to "削除", post_path(post), method: :delete, data: { confirm: "削除しますか？" }, class:"dropdown-item" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="form-style">
        <div class="form-title">
          <h6><strong>編集</strong></h6>
        </div>
        <div class="form-content">
          <%= render "devise/shared/error_messages", resource: @post %>
          <%= render "form" %>
          <%= link_to("戻る", posts_path,  class: "btn btn-secondary btn-lg btn-block btn-back") %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3"></div>
      <div class="col-lg-6 mb-lg-5">
        <%= paginate @posts %>
        <%= link_to "つぶやく", new_post_path, class: "btn btn-primary btn-lg btn-block btn-twitter" %>
        <%= render @posts %>
        <%= paginate @posts %>
      </div>
      <div class="col-lg-3">
        <div class="search-form">
          <div class="form-group row">
            <%= search_form_for @q do |f| %>
              <%= f.search_field :content_cont, class: "form-control", placeholder: "内容を検索する" %>
              <%= f.submit "検索", class: "btn btn-primary btn-twitter" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="form-style">
        <div class="form-title">
          <h6><strong>つぶやき</strong></h6>
        </div>
        <div class="form-content">
          <%= render "devise/shared/error_messages", resource: @post %>
          <%= render "form" %>
          <%= link_to("戻る", posts_path,  class: "btn btn-secondary btn-lg btn-block btn-back") %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6 mb-5">
      <%= link_to "コメントする", new_post_comments_path(@post), class: "btn btn-primary btn-lg btn-block btn-twitter" %>
      <div class="post-detail-content">
        <%= display_user_icon_post(@post.user, "show_image", user_path(@post.user)) %>
        <%= render 'post_header', post: @post %>
        <div class="content">
          <p><%= @post.content %></p>
        </div>
        <%= render 'post_footer', post: @post %>
      </div>
      <%= render partial: 'comment', collection: @post.comments %>
      <%= link_to("戻る", posts_path,  class: "btn btn-secondary btn-lg btn-block btn-back mt-4") %>
    </div>
  </div>
</div>