config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    sessions: 'users/sessions'
  }

  root to: 'tops#index'
  
  resources :users, only: [:index, :show] do
    patch :update_eat_day, on: :member
  end 

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :posts do
    resource :likes, only: [:create, :destroy]
    resource :comments, only: [:new, :create]
    resources :comments, only: [:edit, :update, :destroy]
  end

  resources :informations, only: [:index, :show]
  match '*unmatched_route' => 'application#routing_error', via: :all
end

app/views/layouts/_flash.html.erb
<div class="container flash-style">
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <% flash.each do |key, value| %>
          <div id="flash-message" class="alert alert-<%= key %> alert-dismissible fade show alert-signup" role="alert">
            <%= value.html_safe %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-faded mb-3 fixed-top" style="background-color: #6a318f; height: 90px;">
  <%# ハンバーガーボタン %>
  <button type="button" class="drawer-toggle drawer-hamburger">
    <span class="sr-only">toggle navigation</span>
    <span class="drawer-hamburger-icon"></span>
  </button>
  <%# ナビゲーションの中身 %>
  <nav class="drawer-nav" role="navigation">
    <ul class="drawer-menu">
      <% if user_signed_in? %>
        <%# ログイン時 %>
        <div class="nav-header">
          <%=link_to("", user_path(current_user), class: "fa fa-user-circle menu-icon link_under_none_white", 'aria-hidden': true)%>
          <div class="nav-username">
            <%=link_to(current_user.name, user_path(current_user), class: "link_under_none_white")%>
          </div>
        </div>
        <li><%=link_to(" ホーム", root_path, class: "drawer-menu-item fa fa-home", 'aria-hidden': true)%></li> 
        <li><%=link_to(" マイページ", user_path(current_user), class: "drawer-menu-item fa fa-address-card", 'aria-hidden': true)%></li> 
        <li><%=link_to(" ログアウト", destroy_user_session_path, method: :delete, class: "drawer-menu-item fa fa-sign-out-alt", 'aria-hidden': true)%></li>
        <li><%=link_to(" つぶやき一覧", posts_path,  class: "drawer-menu-item fa fa-comment", 'aria-hidden': true)%></li> 
        <li><%=link_to(" ランキング", users_path,  class: "drawer-menu-item fa fa-trophy", 'aria-hidden': true)%></li> 
        <li><%=link_to(" ニュース一覧", informations_path,  class: "drawer-menu-item fa fa-newspaper", 'aria-hidden': true)%></li>
      <% else %>
        <%# 未ログイン時 %>
        <div class="nav-header">
          <%=link_to("", new_user_session_path, class: "fa fa-user-circle menu-icon link_under_none_white", 'aria-hidden': true)%>
          <div class="nav-username">
            <%=link_to("ゲストさん", new_user_session_path, class: "link_under_none_white")%>
          </div>
        </div>
        <li><%=link_to(" ホーム", root_path, class: "drawer-menu-item fa fa-home", 'aria-hidden': true)%></li> 
        <li><%=link_to(" ログイン", new_user_session_path, class: "drawer-menu-item fa fa-sign-in-alt", 'aria-hidden': true)%></li>
        <li><%=link_to(" アカウント登録", new_user_registration_path, class: "drawer-menu-item fa fa-user-plus", 'aria-hidden': true)%></li>  
        <li><%=link_to(" ゲストログイン", users_guest_sign_in_path, method: :post, class: "drawer-menu-item fa fa-sign-in-alt", 'aria-hidden': true)%></li>
      <% end %> 
    </ul>
  </nav>
  <ul class="navbar-nav ml-auto main-nav align-items-right">
  <% if user_signed_in? %>
    <%# ログイン時 %>
    <%=link_to("Stop Sweets", user_path(current_user), class: "nav navbar-brand font-weight-bold", 'aria-hidden': true)%>
  <% else %>
    <%# 未ログイン時 %>
    <%=link_to("Stop Sweets", root_path, class: "nav navbar-brand font-weight-bold", 'aria-hidden': true)%>
  <% end %> 
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StopSweets</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# drawer.css %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.1/css/drawer.min.css">
    <%# jquery & iScroll %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.1.3/iscroll.min.js"></script>
    <%# drawer.js %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.1/js/drawer.min.js"></script>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body class="drawer drawer--left" style="padding-top: 5rem">
    <header role="banner">
      <%= render 'layouts/header' %>
    </header>
    <main role="main">
      <%= render partial: 'layouts/flash' %>
      <%= yield %>
    </main>
    
    <%# ドロワーメニューの利用宣言 %>
    <script>
      $(document).ready(function() {
      $('.drawer').drawer();
    });
    </script>
  </body>
</html>